# github action of publish package to npm via lerna
name: lerna-publish-package

on:
  push:
    tags:
      - v*

jobs:
#  发布任务不检查代码风格
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: npm run lint
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm i
        echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        npm run tsc:build
        npm run lerna:publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
